version: '3.1'

services:
  nginx:
    container_name: nginx
    build: ./nginx/
    image: flask-users-nginx
    ports:
      - 80:80
    depends_on:
      - users-service

  users-service:
    container_name: users-service
    build: https://github.com/justinaung/flask-microservices-users.git
    image: flask-users-service
    ports:
      - 5001:5000
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    depends_on:
      - users-db

  users-db:
    container_name: users-db
    build: https://github.com/justinaung/flask-microservices-users.git#master:project/db
    image: flask-users-db
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
    healthcheck:
      test: exit 0
